#!/usr/bin/env ansible-playbook
#
# Enable SCP on Cisco IOS
#
---
- hosts: all
  tasks:
  - name: Enable SCP server on Cisco IOS devices
    ios_config:
      lines:
      - ip scp server enable
      - alias exec replace configure replace
      authorize: yes
  - name: Enable configuration archive on Cisco IOS devices
    ios_config:
      parents:
      - archive
      lines:
      - "path flash:"
      authorize: yes
