---
- hosts: ios
  name:  configure loopbacks
  tasks:
  - ios_interface:
      name: Loopback123
      state: up
  - ios_l3_interface:
      name: Loopback123
      ipv4: "{{ ip.Loopback123 }}"
    when: ip is defined and ip.Loopback123 is defined 
