---
- hosts: nxos
  name:  preconfigure VLANs
  tags:  VLAN
  vars:
    ansible_connection: network_cli
  tasks:
  - nxos_vlan:
      vlan_range: "101-199"
      state:   absent
  - nxos_vlan:
      vlan_id:  201
      name:     wrong
      state:    present
