---
- hosts: nxos
  name:  configure VLANs
  vars:
    ansible_connection: network_cli
  tasks:
  - nxos_vlan:
      admin_state: up
      aggregate:
      - { vlan_id: 1, name: "default" }
      - { vlan_id: 100, name: "mgmt" }
      - { vlan_id: 101, name: "web" }
      - { vlan_id: 110, name: "db" }
      purge: yes
