#!/usr/bin/env python

import yaml
import sys
import os
import json
from pprint import pprint

def ly(filename):
    with open(filename) as _:
        return yaml.load(_)

os.system('cls' if os.name == 'nt' else 'clear')

with open(sys.argv[1]) as _:
   text = _.read()

print('### YAML encoding ###')
print text

body = yaml.load(text);
print('### JSON encoding ###')
print json.dumps(body, sort_keys=True, indent=2, separators=(',', ': '))