#!/usr/bin/perl

use strict;
use YAML ();
use File::Slurp;
use Data::Dumper;
use Term::Screen;

sub printout($;$) {
  my ($txt,$nl) = @_;

  $nl ||= 1;
  chomp $txt;          # Remove existing newline and add a new one
  $txt .= "\n" x $nl;  # to ensure all printouts look the same
  $txt =~ s/\n/\r\n/g; # Term::Screen turns STDOUT into raw device
  print $txt;
}

my $scr = new Term::Screen;
$scr->clrscr();
my $fname = shift @ARGV;
my $yaml = read_file($fname) || die "Cannot read YAML object from file $fname: $!";
printout $yaml,2;

my $object = YAML::LoadFile($fname);

$Data::Dumper::Terse = 1; 
my $dashes = "=" x 20;
printout "$dashes PERL object $dashes";
printout Dumper($object);