#!/usr/bin/env python

import yaml
import sys
import os
from pprint import pprint

def ly(filename):
    with open(filename) as _:
        return yaml.load(_)

os.system('cls' if os.name == 'nt' else 'clear')

with open(sys.argv[1]) as _:
   text = _.read()

print('##################################')
print text

body = yaml.load(text);
print('##################################')
pprint(body)